import WebVitals from '@/app/_components/web-vitals'
import '@/styles/globals.css'
import type {Metadata} from 'next'
import localFont from 'next/font/local'

const dvnLuckiestGuy = localFont({
  src: './fonts/DVN-LuckiestGuy-Regular.ttf',
  variable: '--font-dvn-luckiest-guy',
  weight: '400',
  preload: false,
})
const nvnMotherland = localFont({
  src: './fonts/NVN-Motherland-Signature.ttf',
  variable: '--font-nvn-motherland',
  weight: '100 900',
  preload: false,
})

const tripSans = localFont({
  src: [
    {path: './fonts/trip-sans-bold.otf', weight: '700', style: 'normal'},
    {path: './fonts/trip-sans-medium.otf', weight: '500', style: 'normal'},
    {path: './fonts/trip-sans-ultra.otf', weight: '900', style: 'normal'},
    {path: './fonts/trip-sans-variable.ttf', weight: '400', style: 'normal'},
  ],
  variable: '--font-trip-sans',
  preload: true,
})

export const metadata: Metadata = {
  title: 'Tiềm Tour',
  description: 'Generated by create next app',
}

export const viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang={'en'}>
      <body
        className={`${dvnLuckiestGuy.variable} ${nvnMotherland.variable} ${tripSans.variable} antialiased`}
      >
        <WebVitals />
        {children}
      </body>
    </html>
  )
}
